export const moriusThemeTokens = {
  fonts: {
    primary: '"Nunito Sans", "Segoe UI", sans-serif',
  },
  colors: {
    appBackground:
      'radial-gradient(ellipse 64% 30% at 50% -8%, #141f2d 0%, #111111 100%), linear-gradient(44deg, #141f2d 0%, #111111 100%)',
    appBase: '#111111',
    appSurface: '#171716',
    appElevated: '#262624',
    appBorder: '#31302e',
    accent: '#bacad6',
    titleText: '#dbdde7',
    textPrimary: '#dbdde7',
    textSecondary: '#a4adb6',
    buttonHover: '#353432',
    buttonActive: '#353432',
    sendButton: '#bacad7',
    panelGradient: 'linear-gradient(108deg, #31302e 0%, #bacad6 100%)',
    bootBackground: '#111111',
    baseText: '#a4adb6',
  },
  radii: {
    app: 12,
    button: 12,
    menu: 12,
  },
  borders: {
    width: 0.5,
  },
  typography: {
    headingSize: 40,
    subheadingSize: 20,
    bodySize: 16,
  },
  layout: {
    headerHeight: 40,
    headerTopOffset: 20,
    headerSideOffset: 20,
    headerMenuTop: 80,
    headerMenuWidthXs: 252,
    headerMenuWidthMd: 276,
    headerButtonSize: 40,
    headerLogoWidth: 76,
    interfaceGap: 20,
    sectionGap: 20,
    cardsToTitleGap: 40,
    actionButtonSize: 40,
    actionIconSize: 20,
    storyRightCardPadding: 10,
    storyMessageGap: 20,
    iconGap: 20,
    scrollbarOffset: 10,
    contentGap: 20,
    titleTopGap: 40,
    titleBottomGap: 20,
    menuVerticalGap: 10,
    ratingStarGap: 10,
  },
} as const

export const moriusCssVariables = {
  '--morius-app-bg': moriusThemeTokens.colors.appBackground,
  '--morius-app-base': moriusThemeTokens.colors.appBase,
  '--morius-card-bg': moriusThemeTokens.colors.appSurface,
  '--morius-elevated-bg': moriusThemeTokens.colors.appElevated,
  '--morius-card-border': moriusThemeTokens.colors.appBorder,
  '--morius-accent': moriusThemeTokens.colors.accent,
  '--morius-title-text': moriusThemeTokens.colors.titleText,
  '--morius-text-primary': moriusThemeTokens.colors.textPrimary,
  '--morius-text-secondary': moriusThemeTokens.colors.textSecondary,
  '--morius-button-hover': moriusThemeTokens.colors.buttonHover,
  '--morius-button-active': moriusThemeTokens.colors.buttonActive,
  '--morius-send-button-bg': moriusThemeTokens.colors.sendButton,
  '--morius-panel-gradient': moriusThemeTokens.colors.panelGradient,
  '--morius-radius': `${moriusThemeTokens.radii.app}px`,
  '--morius-border-width': `${moriusThemeTokens.borders.width}px`,
  '--morius-heading-size': `${moriusThemeTokens.typography.headingSize}px`,
  '--morius-subheading-size': `${moriusThemeTokens.typography.subheadingSize}px`,
  '--morius-body-size': `${moriusThemeTokens.typography.bodySize}px`,
  '--morius-header-height': `${moriusThemeTokens.layout.headerHeight}px`,
  '--morius-header-top-offset': `${moriusThemeTokens.layout.headerTopOffset}px`,
  '--morius-header-side-offset': `${moriusThemeTokens.layout.headerSideOffset}px`,
  '--morius-header-menu-top': `${moriusThemeTokens.layout.headerMenuTop}px`,
  '--morius-interface-gap': `${moriusThemeTokens.layout.interfaceGap}px`,
  '--morius-section-gap': `${moriusThemeTokens.layout.sectionGap}px`,
  '--morius-cards-title-gap': `${moriusThemeTokens.layout.cardsToTitleGap}px`,
  '--morius-action-size': `${moriusThemeTokens.layout.actionButtonSize}px`,
  '--morius-action-icon-size': `${moriusThemeTokens.layout.actionIconSize}px`,
  '--morius-story-right-padding': `${moriusThemeTokens.layout.storyRightCardPadding}px`,
  '--morius-story-message-gap': `${moriusThemeTokens.layout.storyMessageGap}px`,
  '--morius-icon-gap': `${moriusThemeTokens.layout.iconGap}px`,
  '--morius-scrollbar-offset': `${moriusThemeTokens.layout.scrollbarOffset}px`,
  '--morius-content-gap': `${moriusThemeTokens.layout.contentGap}px`,
  '--morius-title-top-gap': `${moriusThemeTokens.layout.titleTopGap}px`,
  '--morius-title-bottom-gap': `${moriusThemeTokens.layout.titleBottomGap}px`,
  '--morius-menu-vertical-gap': `${moriusThemeTokens.layout.menuVerticalGap}px`,
  '--morius-rating-star-gap': `${moriusThemeTokens.layout.ratingStarGap}px`,
} as const
